version: '3.8'

networks:
  proxy:
    external: true

services:
  planet-app:
    container_name: planet-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxy
